### Generate high quality anime wallpaper
POST http://localhost:5001/api/images/generate
Content-Type: application/json

{
    "prompt": "masterpiece, best quality, ultra-detailed, anime naruto wallpaper with heroes in studio ghibli style, soft lighting, vibrant colors, dynamic composition, cinematic, 8k uhd, high resolution, trending on artstation, professional photography",
    "negative_prompt": "blurry, low quality, distorted, bad anatomy, bad hands, text, error, missing fingers, extra digit, fewer digits, cropped, worst quality, low quality, normal quality, jpeg artifacts, signature, watermark, username, blurry, artist name",
    "width": 1024,
    "height": 512,
    "generator_type": "fusion_brain"
}

### Get task status by ID
GET http://localhost:5001/api/images/status/da82a177-b673-435f-98e0-5796410fdc3e
Content-Type: application/json

### Test Feature Extraction
POST http://localhost:5001/api/images/extract-features
Content-Type: application/json

{
    "image_path": "static/images/5c8e4a61-8ad2-4f40-ab3e-18f056622f41.jpg"
}

###
GET http://localhost:5001/api/images/generators

# generate svg
###
POST http://localhost:5001/api/generate
Content-Type: application/json

{
   
  "prompt": "Generate a complete animated SVG XML text using SMIL animation. The SVG must include the <svg> root tag and valid SMIL animations depicting a natural or abstract scene, such as 'twinkling stars in a night sky' or 'leaves falling gently in autumn breeze'. The output must be concise but self-contained, ready to be saved as an .svg file and rendered as animation."
}

# convert  svg to png

### Generate Lottie JSON animation
POST http://localhost:5001/api/generate
Content-Type: application/json

{
  "prompt": "Create an animated via CSS SVG illustration of a rocket launching into space. The rocket should have moving flames at the bottom, dynamic exhaust effects, and a trail that follows it as it ascends. Incorporate twinkling stars in the background that appear randomly and animate softly to add depth to the scene.Feel free to customize or specify specific elements youd like to include!"}

### Convert animated SVG file to GIF
POST http://localhost:5001/api/generate/svg-file-to-gif
