services:
  redis:
    image: redis:7.2-alpine
    command: redis-server --requirepass ${REDIS_PASSWORD}
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    restart: unless-stopped

  celery_worker:
    build: 
      context: ./server_generator
      dockerfile: Dockerfile
    command: celery -A celery_config.celery_app worker --loglevel=info --concurrency=1 --pythonpath=/app
    depends_on:
      - redis
    restart: unless-stopped

volumes:
  redis_data: 